"""
Property tests for SteeringFileGenerator LLM call behavior.

Tests that SteeringFileGenerator calls LLM exactly once per template
and implements retry-once behavior correctly.

Requirements: 1.1, 1.3, 6.5
"""

import pytest
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, call

from hiveforge.steering.steering_file_generator import SteeringFileGenerator
from hiveforge.steering.context_assembler import ContextAssembler
from hiveforge.steering.prompt_builder import PromptBuilder
from hiveforge.steering.models import (
    CodeAnalysisFacts,
    Dependency,
    GenerationContext,
    NamingConventions,
    ParsedDocument,
)


class TestLLMCallsProperty:
    """
    Property 1: LLM called for every template.
    
    For any successful run, LLMProvider.complete() must be called exactly 8 times
    with no regex path taken.
    
    Requirements: 1.1
    """
    
    @pytest.mark.asyncio
    async def test_llm_called_exactly_8_times_for_all_templates(self, tmp_path):
        """
        Test that LLM is called exactly once per template (8 times total).
        
        Requirements: 1.1
        """
        # Create mock LLM provider
        mock_llm = MagicMock()
        mock_llm.is_available.return_value = True
        
        # Mock complete() to return valid steering file content
        async def mock_complete(**kwargs):
            return "# Test Steering File\n\n## Section 1\n\nContent here.\n\n## Section 2\n\nMore content."
        
        mock_llm.complete = AsyncMock(side_effect=mock_complete)
        
        # Create generator
        generator = SteeringFileGenerator(mock_llm)
        
        # Create minimal context assembler and prompt builder
        context_assembler = ContextAssembler()
        prompt_builder = PromptBuilder()
        
        # Create minimal code facts
        code_facts = CodeAnalysisFacts(
            primary_language="Python 3.11",
            frameworks=[],
            dependencies=[],
            architecture_pattern="custom",
            has_tests=False,
            test_framework=None,
            api_type=None,
            database=None,
            entry_points=[],
            naming_conventions=NamingConventions(),
            directory_structure="",
        )
        
        # Mock the internal methods to avoid actual validation
        generator._validate_draft = MagicMock(return_value=[])
        generator._check_duplicate_paragraphs = MagicMock(return_value=[])
        
        # Generate all files
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        
        result = await generator.generate_all_files(
            context_assembler=context_assembler,
            prompt_builder=prompt_builder,
            code_facts=code_facts,
            source_docs=[],
            existing_steering={},
            delta=None,
            user_intent=None,
            use_case="new_from_docs",
            output_dir=output_dir,
        )
        
        # Assert LLM was called exactly 8 times (once per template)
        assert mock_llm.complete.call_count == 8, (
            f"Expected LLM to be called 8 times (once per template), "
            f"but was called {mock_llm.complete.call_count} times"
        )
        
        # Assert result is successful
        assert result.success is True
        assert len(result.files_written) == 8
        assert len(result.validation_errors) == 0
    
    @pytest.mark.asyncio
    async def test_llm_called_for_each_template_in_order(self, tmp_path):
        """
        Test that LLM is called for each template in the correct sequential order.
        
        Requirements: 1.1
        """
        # Create mock LLM provider
        mock_llm = MagicMock()
        mock_llm.is_available.return_value = True
        
        # Track which templates were generated by checking system prompts
        generated_templates = []
        
        async def mock_complete(**kwargs):
            # The template name is passed to PromptBuilder which includes it in prompts
            # We'll track calls by counting them since they happen in order
            generated_templates.append(len(generated_templates))
            return "# Test Steering File\n\n## Section 1\n\nContent here."
        
        mock_llm.complete = AsyncMock(side_effect=mock_complete)
        
        # Create generator
        generator = SteeringFileGenerator(mock_llm)
        
        # Create minimal context assembler and prompt builder
        context_assembler = ContextAssembler()
        prompt_builder = PromptBuilder()
        
        # Create minimal code facts
        code_facts = CodeAnalysisFacts(
            primary_language="Python 3.11",
            frameworks=[],
            dependencies=[],
            architecture_pattern="custom",
            has_tests=False,
            test_framework=None,
            api_type=None,
            database=None,
            entry_points=[],
            naming_conventions=NamingConventions(),
            directory_structure="",
        )
        
        # Mock validation
        generator._validate_draft = MagicMock(return_value=[])
        generator._check_duplicate_paragraphs = MagicMock(return_value=[])
        
        # Generate all files
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        
        result = await generator.generate_all_files(
            context_assembler=context_assembler,
            prompt_builder=prompt_builder,
            code_facts=code_facts,
            source_docs=[],
            existing_steering={},
            delta=None,
            user_intent=None,
            use_case="new_from_docs",
            output_dir=output_dir,
        )
        
        # Assert LLM was called exactly 8 times (once per template in order)
        assert len(generated_templates) == 8, (
            f"Expected 8 templates to be generated, got {len(generated_templates)}"
        )
        
        # Assert result is successful
        assert result.success is True
        assert len(result.files_written) == 8


class TestRetryOnceProperty:
    """
    Property 2: Retry exactly once on empty/malformed response.
    
    For any template returning empty or malformed Markdown, build_simplified()
    is called exactly once; hallucination errors must never trigger build_simplified().
    
    Requirements: 1.3, 6.5
    """
    
    @pytest.mark.asyncio
    async def test_retry_once_on_empty_response(self, tmp_path):
        """
        Test that empty LLM response triggers exactly one retry with simplified prompt.
        
        Requirements: 1.3, 6.5
        """
        # Create mock LLM provider
        mock_llm = MagicMock()
        mock_llm.is_available.return_value = True
        
        # First call returns empty, second call returns valid content
        call_count = 0
        
        async def mock_complete(**kwargs):
            nonlocal call_count
            call_count += 1
            
            # Only first call for first template returns empty
            # All subsequent calls return valid content
            if call_count == 1:
                # First call returns empty
                return ""
            else:
                # Subsequent calls return valid content
                return "# Test Steering File\n\n## Section 1\n\nContent here."
        
        mock_llm.complete = AsyncMock(side_effect=mock_complete)
        
        # Create generator
        generator = SteeringFileGenerator(mock_llm)
        
        # Create mock prompt builder to track simplified calls
        prompt_builder = PromptBuilder()
        original_build = prompt_builder.build
        original_build_simplified = prompt_builder.build_simplified
        
        build_calls = []
        simplified_calls = []
        
        def track_build(*args, **kwargs):
            build_calls.append(args)
            return original_build(*args, **kwargs)
        
        def track_simplified(*args, **kwargs):
            simplified_calls.append(args)
            return original_build_simplified(*args, **kwargs)
        
        prompt_builder.build = track_build
        prompt_builder.build_simplified = track_simplified
        
        # Create minimal context assembler
        context_assembler = ContextAssembler()
        
        # Create minimal code facts
        code_facts = CodeAnalysisFacts(
            primary_language="Python 3.11",
            frameworks=[],
            dependencies=[],
            architecture_pattern="custom",
            has_tests=False,
            test_framework=None,
            api_type=None,
            database=None,
            entry_points=[],
            naming_conventions=NamingConventions(),
            directory_structure="",
        )
        
        # Mock validation
        generator._validate_draft = MagicMock(return_value=[])
        generator._check_duplicate_paragraphs = MagicMock(return_value=[])
        
        # Generate all files
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        
        result = await generator.generate_all_files(
            context_assembler=context_assembler,
            prompt_builder=prompt_builder,
            code_facts=code_facts,
            source_docs=[],
            existing_steering={},
            delta=None,
            user_intent=None,
            use_case="new_from_docs",
            output_dir=output_dir,
        )
        
        # Assert build_simplified was called exactly once (for first template retry)
        assert len(simplified_calls) == 1, (
            f"Expected build_simplified to be called 1 time (for first template retry), "
            f"but was called {len(simplified_calls)} times"
        )
        
        # Assert LLM was called 9 times (1 initial + 1 retry for first template, then 7 more)
        assert mock_llm.complete.call_count == 9, (
            f"Expected LLM to be called 9 times (1 initial + 1 retry + 7 more), "
            f"but was called {mock_llm.complete.call_count} times"
        )
        
        # Assert result is successful
        assert result.success is True
    
    @pytest.mark.asyncio
    async def test_no_retry_on_hallucination_error(self, tmp_path):
        """
        Test that hallucination errors do NOT trigger retry with simplified prompt.
        
        Requirements: 1.3, 6.5
        """
        # Create mock LLM provider
        mock_llm = MagicMock()
        mock_llm.is_available.return_value = True
        
        # Return content with hallucination (wrong database)
        async def mock_complete(**kwargs):
            return """# Tech Stack

## Database
We use MongoDB for all data storage.

## Backend Framework
We use FastAPI for the backend.
"""
        
        mock_llm.complete = AsyncMock(side_effect=mock_complete)
        
        # Create generator
        generator = SteeringFileGenerator(mock_llm)
        
        # Create mock prompt builder to track simplified calls
        prompt_builder = PromptBuilder()
        original_build_simplified = prompt_builder.build_simplified
        
        simplified_calls = []
        
        def track_simplified(*args, **kwargs):
            simplified_calls.append(args)
            return original_build_simplified(*args, **kwargs)
        
        prompt_builder.build_simplified = track_simplified
        
        # Create minimal context assembler
        context_assembler = ContextAssembler()
        
        # Create code facts with PostgreSQL (contradicts MongoDB in LLM output)
        code_facts = CodeAnalysisFacts(
            primary_language="Python 3.11",
            frameworks=["FastAPI"],
            dependencies=[],
            architecture_pattern="custom",
            has_tests=False,
            test_framework=None,
            api_type=None,
            database="PostgreSQL",  # This contradicts the LLM output
            entry_points=[],
            naming_conventions=NamingConventions(),
            directory_structure="",
        )
        
        # Mock duplicate paragraph check (pass)
        generator._check_duplicate_paragraphs = MagicMock(return_value=[])
        
        # Generate all files
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        
        result = await generator.generate_all_files(
            context_assembler=context_assembler,
            prompt_builder=prompt_builder,
            code_facts=code_facts,
            source_docs=[],
            existing_steering={},
            delta=None,
            user_intent=None,
            use_case="new_from_docs",
            output_dir=output_dir,
        )
        
        # Assert build_simplified was NEVER called (hallucination should abort immediately)
        assert len(simplified_calls) == 0, (
            f"Expected build_simplified to never be called on hallucination error, "
            f"but was called {len(simplified_calls)} times"
        )
        
        # Assert result is failure
        assert result.success is False
        assert len(result.validation_errors) > 0
        assert any("MongoDB" in error or "database" in error.lower() 
                  for error in result.validation_errors)
    
    @pytest.mark.asyncio
    async def test_fail_after_one_retry_on_persistent_empty_response(self, tmp_path):
        """
        Test that persistent empty responses fail after exactly one retry.
        
        Requirements: 1.3, 6.5
        """
        # Create mock LLM provider that always returns empty
        mock_llm = MagicMock()
        mock_llm.is_available.return_value = True
        
        async def mock_complete(**kwargs):
            return ""  # Always empty
        
        mock_llm.complete = AsyncMock(side_effect=mock_complete)
        
        # Create generator
        generator = SteeringFileGenerator(mock_llm)
        
        # Create minimal context assembler and prompt builder
        context_assembler = ContextAssembler()
        prompt_builder = PromptBuilder()
        
        # Create minimal code facts
        code_facts = CodeAnalysisFacts(
            primary_language="Python 3.11",
            frameworks=[],
            dependencies=[],
            architecture_pattern="custom",
            has_tests=False,
            test_framework=None,
            api_type=None,
            database=None,
            entry_points=[],
            naming_conventions=NamingConventions(),
            directory_structure="",
        )
        
        # Generate all files
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        
        result = await generator.generate_all_files(
            context_assembler=context_assembler,
            prompt_builder=prompt_builder,
            code_facts=code_facts,
            source_docs=[],
            existing_steering={},
            delta=None,
            user_intent=None,
            use_case="new_from_docs",
            output_dir=output_dir,
        )
        
        # Assert LLM was called exactly 2 times for first template (initial + 1 retry)
        # Then generation should abort
        assert mock_llm.complete.call_count == 2, (
            f"Expected LLM to be called 2 times (initial + 1 retry for first template), "
            f"but was called {mock_llm.complete.call_count} times"
        )
        
        # Assert result is failure
        assert result.success is False
        assert len(result.validation_errors) > 0
        assert any("empty" in error.lower() or "malformed" in error.lower() 
                  for error in result.validation_errors)
