"""
Content Tagger for Steering File Generation.

This module provides the ContentTagger class that adds metadata headers,
inferred section tags, and low confidence warnings to generated steering files.

The tagging system helps users identify which content was inferred by the LLM
and requires verification, improving transparency and trust in the generated files.
"""

import re
from datetime import datetime, timezone
from typing import Dict, List, Any
from .confidence import ConfidenceScore


class ContentTagger:
    """
    Tags inferred content and adds metadata to steering files.
    
    The ContentTagger adds three types of enhancements to generated content:
    1. YAML frontmatter with confidence metadata
    2. HTML comment tags around inferred sections
    3. Prominent warnings for low-confidence files
    
    All tagging preserves the original markdown structure and formatting.
    """
    
    def tag_inferred_sections(
        self,
        content: str,
        inferred_sections: List[str]
    ) -> str:
        """
        Add [INFERRED] tags to specified sections in markdown content.
        
        This method identifies section headers matching the inferred section names
        and wraps the section content with HTML comment tags to indicate it was
        generated by LLM inference rather than derived from source documents.
        
        Args:
            content: Original markdown content
            inferred_sections: List of section names that were inferred
        
        Returns:
            Content with inferred sections tagged
            
        Example:
            >>> tagger = ContentTagger()
            >>> content = "## Problem Statement\\nUsers struggle...\\n## Solution\\n..."
            >>> tagged = tagger.tag_inferred_sections(content, ["Problem Statement"])
            >>> print(tagged)
            ## Problem Statement
            <!-- INFERRED: Please verify this section -->
            Users struggle...
            <!-- END INFERRED -->
            ## Solution
            ...
        """
        if not inferred_sections:
            return content
        
        lines = content.split('\n')
        result = []
        in_inferred_section = False
        current_section_level = 0
        
        for i, line in enumerate(lines):
            # Check if this is a header line
            header_match = re.match(r'^(#{1,6})\s+(.+)$', line)
            
            if header_match:
                header_level = len(header_match.group(1))
                header_text = header_match.group(2).strip()
                
                # Close previous inferred section if we're at same or higher level
                if in_inferred_section and header_level <= current_section_level:
                    result.append('<!-- END INFERRED -->')
                    result.append('')
                    in_inferred_section = False
                
                # Add the header line
                result.append(line)
                
                # Check if this header starts an inferred section
                if header_text in inferred_sections:
                    result.append('<!-- INFERRED: Please verify this section -->')
                    in_inferred_section = True
                    current_section_level = header_level
            else:
                # Regular content line
                result.append(line)
        
        # Close any remaining inferred section at end of file
        if in_inferred_section:
            result.append('<!-- END INFERRED -->')
        
        return '\n'.join(result)
    
    def add_metadata_header(
        self,
        content: str,
        confidence: ConfidenceScore,
        metadata: Dict[str, Any]
    ) -> str:
        """
        Add YAML frontmatter with confidence metadata to the content.
        
        The frontmatter includes generation metadata, confidence scores, and
        source information to help users understand the provenance of the content.
        
        Args:
            content: Original markdown content
            confidence: Pre-calculated confidence score
            metadata: Additional metadata to include (e.g., source_docs_path)
        
        Returns:
            Content with YAML frontmatter prepended
            
        Example:
            >>> tagger = ContentTagger()
            >>> score = ConfidenceScore(0.65, "medium", {...}, ["Problem Statement"])
            >>> metadata = {"source_documents": 3, "code_analysis": True}
            >>> tagged = tagger.add_metadata_header(content, score, metadata)
            >>> print(tagged[:100])
            ---
            generated_by: hiveforge v2.2.0
            generated_at: 2026-02-19T10:30:00Z
            ...
        """
        # Build frontmatter
        frontmatter_lines = ['---']
        
        # Add generation info
        frontmatter_lines.append('generated_by: hiveforge v2.2.0')
        frontmatter_lines.append(f'generated_at: {datetime.now(timezone.utc).isoformat()}')
        
        # Add source document count
        source_docs = metadata.get('source_documents', 0)
        frontmatter_lines.append(f'source_documents: {source_docs}')
        
        # Add source_docs_path if provided
        if 'source_docs_path' in metadata:
            frontmatter_lines.append(f'source_docs_path: {metadata["source_docs_path"]}')
        
        # Add code analysis flag
        code_analysis = metadata.get('code_analysis', False)
        frontmatter_lines.append(f'code_analysis: {str(code_analysis).lower()}')
        
        # Add confidence information
        frontmatter_lines.append('confidence:')
        frontmatter_lines.append(f'  overall: {confidence.overall:.2f}')
        frontmatter_lines.append(f'  level: {confidence.level}')
        
        # Add source breakdown if available
        if confidence.sources:
            frontmatter_lines.append('  sources:')
            for source_type, weight in confidence.sources.items():
                frontmatter_lines.append(f'    {source_type}: {weight:.2f}')
        
        # Add inferred sections if any
        if confidence.inferred_sections:
            frontmatter_lines.append('  inferred_sections:')
            for section in confidence.inferred_sections:
                # Escape section names with special characters
                escaped_section = section.replace('"', '\\"')
                frontmatter_lines.append(f'    - "{escaped_section}"')
        
        frontmatter_lines.append('---')
        frontmatter_lines.append('')  # Blank line after frontmatter
        
        # Combine frontmatter with content
        frontmatter = '\n'.join(frontmatter_lines)
        
        # Remove existing frontmatter if present
        content_without_frontmatter = self._remove_existing_frontmatter(content)
        
        return frontmatter + content_without_frontmatter
    
    def add_low_confidence_warning(
        self,
        content: str
    ) -> str:
        """
        Add a prominent warning banner for low-confidence files.
        
        This warning appears at the top of the file (after frontmatter) to
        alert users that most content was inferred and needs verification.
        
        Args:
            content: Content with frontmatter already added
        
        Returns:
            Content with warning banner inserted after frontmatter
            
        Example:
            >>> tagger = ContentTagger()
            >>> content = "---\\ngenerated_by: hiveforge\\n---\\n\\n# Title\\n..."
            >>> warned = tagger.add_low_confidence_warning(content)
            >>> print(warned)
            ---
            generated_by: hiveforge
            ---
            
            > ⚠️ **LOW CONFIDENCE**: This file was generated with limited source material.
            > Most content is inferred from code analysis. Please review and update...
        """
        warning = (
            '\n> ⚠️ **LOW CONFIDENCE**: This file was generated with limited source material.\n'
            '> Most content is inferred from code analysis. Please review and update with '
            'actual project information.\n'
        )
        
        # Find the end of frontmatter
        lines = content.split('\n')
        frontmatter_end = -1
        in_frontmatter = False
        
        for i, line in enumerate(lines):
            if i == 0 and line.strip() == '---':
                in_frontmatter = True
            elif in_frontmatter and line.strip() == '---':
                frontmatter_end = i
                break
        
        if frontmatter_end >= 0:
            # Insert warning after frontmatter
            lines.insert(frontmatter_end + 1, warning)
            return '\n'.join(lines)
        else:
            # No frontmatter, add warning at the beginning
            return warning + '\n' + content
    
    def _remove_existing_frontmatter(self, content: str) -> str:
        """
        Remove existing YAML frontmatter from content if present.
        
        Args:
            content: Content that may have frontmatter
        
        Returns:
            Content without frontmatter
        """
        lines = content.split('\n')
        
        # Check if content starts with frontmatter
        if not lines or lines[0].strip() != '---':
            return content
        
        # Find the closing ---
        for i in range(1, len(lines)):
            if lines[i].strip() == '---':
                # Return content after frontmatter
                return '\n'.join(lines[i + 1:])
        
        # No closing ---, return original content
        return content
    
    def tag_content(
        self,
        content: str,
        confidence: ConfidenceScore,
        metadata: Dict[str, Any]
    ) -> str:
        """
        Apply all tagging operations to content in the correct order.
        
        This is a convenience method that applies all tagging operations:
        1. Tag inferred sections with HTML comments
        2. Add YAML frontmatter with metadata
        3. Add low confidence warning if needed
        
        Args:
            content: Original markdown content
            confidence: Pre-calculated confidence score
            metadata: Additional metadata to include
        
        Returns:
            Fully tagged content ready for writing to file
            
        Example:
            >>> tagger = ContentTagger()
            >>> score = ConfidenceScore(0.3, "low", {...}, ["Problem Statement"])
            >>> metadata = {"source_documents": 0, "code_analysis": True}
            >>> tagged = tagger.tag_content(content, score, metadata)
        """
        # Step 1: Tag inferred sections
        tagged_content = self.tag_inferred_sections(
            content,
            confidence.inferred_sections
        )
        
        # Step 2: Add metadata header
        tagged_content = self.add_metadata_header(
            tagged_content,
            confidence,
            metadata
        )
        
        # Step 3: Add low confidence warning if needed
        if confidence.level == "low":
            tagged_content = self.add_low_confidence_warning(tagged_content)
        
        return tagged_content
